SELECT * FROM ORDERS;

SELECT REGION,
	SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY REGION;

SELECT REGION,
	SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    ROUND((SUM(PROFIT)/SUM(SALES))*100,2) AS PROFIT_MARGIN_PCT
FROM ORDERS
GROUP BY REGION;

SELECT REGION,
	SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    ROUND((SUM(PROFIT)/SUM(SALES))*100,2) AS PROFIT_MARGIN_PCT,
    RANK()OVER(ORDER BY ROUND((SUM(PROFIT)/SUM(SALES))*100,2) DESC) AS REGION_RANK
FROM ORDERS
GROUP BY REGION;

SELECT REGION,
	SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    ROUND((SUM(PROFIT)/SUM(SALES))*100,2) AS PROFIT_MARGIN_PCT,
    dense_rank
    ()OVER(ORDER BY ROUND((SUM(PROFIT)/SUM(SALES))*100,2) DESC) AS REGION_DENSERANK
FROM ORDERS
GROUP BY REGION;

SELECT REGION,
	SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    ROUND((SUM(PROFIT)/SUM(SALES))*100,2) AS PROFIT_MARGIN_PCT,
    dense_rank
    ()OVER(ORDER BY ROUND((SUM(PROFIT)/SUM(SALES))*100,2) DESC) AS performance_RANK
FROM ORDERS
GROUP BY REGION;
