SELECT COUNT(*) FROM ORDERS;

SELECT * FROM ORDERS;

SELECT *
FROM ORDERS
WHERE DISCOUNT > 0.30
ORDER BY DISCOUNT DESC;

SELECT COUNT(*) as HIGH_DISCOUNT_ORDERS
FROM ORDERS
WHERE DISCOUNT > 0.30
ORDER BY DISCOUNT DESC; 

SELECT Avg(profit) as AVG_LOSS_PER_ORDER
FROM ORDERS;

SELECT Avg(profit) as AVG_LOSS_PER_ORDER
FROM ORDERS
WHERE DISCOUNT > 0.30
	AND PROFIT < 0;
    
SELECT COUNT(*) AS LOSS_ORDERS,
	SUM(PROFIT) AS TOTAL_LOSS
FROM ORDERS
WHERE DISCOUNT > 0.30
	AND PROFIT < 0;
    
SELECT PRODUCT_NAME,
	SUM(PROFIT) AS TOTAL_PROFIT,
    SUM(SALES) AS TOTAL_SALES,
    AVG(DISCOUNT) AS AVG_DISCOUNT
FROM ORDERS
GROUP BY PRODUCT_NAME
HAVING SUM(PROFIT) < 0
ORDER BY TOTAL_PROFIT
LIMIT 10;
